### ISSUE TITLE
Migrate to mixlib-log for logging

### ISSUE THREAD

**Issue by tas50** [chef/chef-api#74]
Remove the Logify depdendency

**Comment by tecracer-theinen** [comment]
Bump for this one.

I tried using chef-api on windows and it fails because logify uses git to collect its files in its gemspec. As there's not GIT on Windows by default, I can't even execute `inspec plugin list` without getting:

`STDERR: Invalid gemspec in [C:/Users/Administrator/.inspec/gems/2.6.0/gems/logify-0.2.0/logify.gemspec]: No such file or directory - git ls-files -z`

That's how I discovered this issue in the end :)

**Comment by tas50** [comment]
Done. Thanks @tecracer-theinen
